### ISSUE TITLE
I want a key binding for list selection

### ISSUE THREAD

**Issue by minorugh** [blue0513/point-history#1]
Thank you for the wonderful application.
I want a key binding to select the point-show-history list.

1. tab / backtab with cycle
2. j / k  or  n / p
3. defcustom function

Hope is No.1

**Comment by blue0513** [comment]
Thanks for creating the issue!  
Ok, I will implement such a function, and make customizable bindings :+1:

**Comment by blue0513** [comment]
@minorugh I created PR for this issue. Plz check it like below :+1:
```
$ git fetch --all
$ git checkout feature/add-keymap
$ git pull
```
After restart Emacs, you can move line by `n`, `p`, `tab`, `ctrl-tab`.

When you want to change the keymap in `point-history-show-buffer`, edit init.el as below.
```elisp
(define-key point-history-show-mode-map (kbd "n") 'point-history-next-line)
(define-key point-history-show-mode-map (kbd "p") 'point-history-prev-line)
```

**Comment by minorugh** [comment]
Thank you for your quick response.
I tried, but I get the following error.

'Symbol's function definition is void: current-line'

Me, Emacs26.1  on MacOS. Is it because of the environment?

**Comment by blue0513** [comment]
@minorugh Hmm... My checked environment is also MacOS & Emacs 26.1.  
`(current-line)` is already defined in `array.el`, so I misunderstood such errors won't occur.

I pushed a fix-commit. Plz `git pull` again 🙇 

~Plz check below:~

~1. What happens by evaluating `(current-line)` in any `.el` file by `C-x C-e` ? (see: 
https://www.gnu.org/software/emacs/manual/html_node/emacs/Lisp-Eval.html)~
~2. What happens by evaluating `(line-number-at-pos)` and `(count-lines (point-min) (line-beginning-position))` ?~

**Comment by minorugh** [comment]
The error has been resolved. I am very happy. Thank you It was a lot.

**Comment by blue0513** [comment]
@minorugh Cool! I'll merge that PR. You can use master branch after that! :tada:

**Comment by minorugh** [comment]
本当にありがとうございました。
この類はいろいろ多種存在しますが、動作の機敏さを含めて秀逸だと思います。
いろいろ使ってみて私の場合は、key-bindは、下記が一番使いやすいと感じました。
<SPC> : next-line
    b : prev-line

でも、Userのkey操作習慣によって好みが分かれるでしょうね。
カスタマイズできるようにしてくださったので助かります。

----
やまだみのる
