### ISSUE TITLE
List is not hidden by `<RET>`.

### ISSUE THREAD

**Issue by minorugh** [blue0513/point-history#11]
Initially, I think that the list was automatically hidden when I
selected from the LIST and pressed the ret-key ...

**Comment by blue0513** [comment]
@minorugh Hmmm... last night, I fixed this problem. Let's try it on the latest master branch.

**Comment by minorugh** [comment]
We replaced it with the latest one and confirmed it here. I'm sorry I didn't notice it.
Thanks!

**Comment by blue0513** [comment]
Don't worry 👍
