### ISSUE TITLE
Preview behavior when returning to the first line in list rotation

### ISSUE THREAD

**Issue by minorugh** [blue0513/point-history#12]
The preview point does not move only when returning from the list end to the first line.
It is normal after the second line.

**Comment by blue0513** [comment]
@minorugh Thx for reporting!  
I merged #13. Plz check it on the latest master branch.

**Comment by minorugh** [comment]
I confirmed that the measures were perfect.
Thank you for your speedy response.

**Comment by blue0513** [comment]
Thx too
