### ISSUE TITLE
I want to hide the buffer that returns nil to the list.

### ISSUE THREAD

**Issue by minorugh** [blue0513/point-history#4]
Thank's for your kind support.
The kill-buffered buffer and new file buffer, etc. will be displayed as 'nil:'.

Is it possible to hide these from the list?
Sorry for the poor English.

**Comment by blue0513** [comment]
@minorugh Yeah, I got to know what you say.

<img width="292" alt="Screen Shot 2019-04-14 at 20 28 35" src="https://user-images.githubusercontent.com/8979468/56092214-ea270380-5ef3-11e9-904b-015964062375.png">

I agree with the idea to remove `nil:` from the list 👍 
I'll implement it to solve the problem if I can.

But even I create a new file and stay over 1 sec in the file, it was not displayed as `nil:`. How can I reproduce _new_file_buffer_ problem?

**Comment by minorugh** [comment]
It seems like it was my mistake to be 'nil' when creating a new file.
I'm really sorry.

**Comment by blue0513** [comment]
@minorugh I made a PR for this issue! https://github.com/blue0513/point-history/pull/6. Plz try it. 

```
$ git fetch --all
$ git checkout feature/remove-killed-buffer-from-list
$ git pull
```

After restart Emacs, you don't see `nil:` in the list.

**Comment by minorugh** [comment]
I confirmed the operation now. There is no problem at all. wonderful!
`point-histry` is one of my treasures.

Thank you for working in the middle of the night.

**Comment by blue0513** [comment]
Cool!
