### ISSUE TITLE
The buffer at the cursor position to displayed in other-window.

### ISSUE THREAD

**Issue by minorugh** [blue0513/point-history#5]
I had such a dream last night.  If you move the cursor on the List,
the target buffer will be displayed in other-window one after another.
Specifically, it behaves like counsel-switch-buffer.

I don't think there are any more embarrassing demands,
but I'm very happy that my dreams come true.

**Comment by blue0513** [comment]
I didn't know `counsel-switch-buffer`, but it seems cool.  
I'll check it deeply and try to implement if possible :+1:

**Comment by minorugh** [comment]
Maybe that would be a breakthrough development.
In that case, I will make the height of point-history-show about 15 for the other-window.

**Comment by blue0513** [comment]
@minorugh I made PR https://github.com/blue0513/point-history/pull/8 for this issue :tada: Plz check it.

```
$ git fetch --all
$ git checkout feature/preview-buffer
$ git pull
```
After restart Emacs, you can use it.

**Comment by blue0513** [comment]
merged!
