### ISSUE TITLE
Ignore specific buffers

### ISSUE THREAD

**Issue by minorugh** [blue0513/point-history#9]
Thank you for always fulfilling my desires.
I want a setting to ignore specific buffers.

**Comment by blue0513** [comment]
you mean specific `modes` right?

**Comment by minorugh** [comment]
exactly.
We think of `dired-mode`  and  `direx:direx-modo (tree)`

**Comment by blue0513** [comment]
@minorugh I made PR #10. Plz check it by reading README.md.

```
$ git fetch --all
$ git checkout feature/ignore-major-mode
$ git pull
```

And you should edit init.el to ignore some major-modes.

```elisp
(setq point-history-ignore-major-mode '(emacs-lisp-mode ruby-mode))
```

**Comment by minorugh** [comment]
@blue0513 

What a wonderful!
Perfect!  You are like a magician (^ o ^)

I'm sorry I went to bed last night.

**Comment by blue0513** [comment]
Cool
